version: "3.9"
services:
  postgres:
    image: postgres:16.1
    env_file: .env
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "${DATABASE_PORT}:5432"